try:
    from pyb import SPI
except ImportError:
    from machine import SPI


SPI_DUMMY_INT = 0x00
SPI_TRANSFER_LEN = 1
SPI_HOLD_US = 50

SPI_DEFAULT_BAUDRATE = 10000000  # 10MHz
SPI_DEFAULT_FIRSTBIT = SPI.MSB
SPI_DEFAULT_POLARITY = 0
SPI_DEFAULT_PHASE = 0

SPI_ESP32_HARDWARE_CHANNEL = 1
SPI_ESP32_SCK_PIN = 14
SPI_ESP32_MOSI_PIN = 13
SPI_ESP32_MISO_PIN = 12
SPI_ESP32_CS_PIN = 23
